[package]
name = "otc_meme_router"
version = "0.1.0"
cairo-version = "2.8.4"
scarb-version = "2.8.4"

[dependencies]
starknet = "2.8.4"
alexandria_ascii = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5" }   # v2.8.2
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5" } # v2.8.2
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria.git", rev = "95d98a5" }    # v2.8.2
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib", rev = "86d7ccd" } # v2.8.2
openzeppelin = "0.19.0" # v2.8.4

[lib]

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true

[tool.fmt]
sort-module-level-items = true
